calculator/urls.py
from django.urls import path

from calculator import views

urlpatterns = [
    path('', views.index, name='index'),
    path('clients/create', views.ClientCreateView.as_view(), name='create_client'),
    path('clients/all', views.ClientListView.as_view(), name='clients'),
    path('clients/<int:pk>/', views.ClientDetailView.as_view(), name='client_detail'),
    path('invoice/create', views.InvoiceCreateView.as_view(), name='create_invoice'),
    path('invoice/<int:pk>/', views.InvoiceDetailView.as_view(), name='invoice_detail'),
    path('client/export/<int:client_id>', views.ClientExportView.as_view(), name='client_export'),
    path('export-checked-clients/', views.CheckedClientsExportView.as_view(), name='export_checked_clients'),
]

energyCalc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calculator.urls')),
    path('users/', include('users.urls')),
    path('superuser/', include('admin_panel.urls')),
]

users/urls.py
from django.urls import path, include
from users import views
from users.views import CustomPasswordChangeView

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('me/', views.ProfileView.as_view(), name='me'),
    path('me/edit/', views.ProfileEditView.as_view(), name='edit'),
    path('me/change-password/', CustomPasswordChangeView.as_view(), name='change_password'),
]

calculator/models.py
from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import models


# Create your models here.
class Client(models.Model):
    LOCAL_BUDGET = 'Местный бюджет'
    STATE_BUDGET = 'Республиканский бюджет'
    LEGAL_ENTITY = 'Юридическое лицо'

    CONSUMER_GROUP_CHOICES = [
        (LOCAL_BUDGET, 'Местный бюджет'),
        (STATE_BUDGET, 'Республиканский бюджет'),
        (LEGAL_ENTITY, 'Юридическое лицо'),
    ]

    name = models.CharField(max_length=100, verbose_name="Наименование")
    bin_number = models.CharField(max_length=12, verbose_name="БИН номер")
    information = models.CharField(max_length=256, verbose_name="Информация ПКУ", blank=True)
    contract_number = models.CharField(max_length=50, verbose_name="Номер договора")
    contract_date = models.DateField(verbose_name="Дата акта")
    location = models.CharField(max_length=128, verbose_name="Местоположение ПКУ", blank=True)
    notes = models.CharField(max_length=256, verbose_name="Примечания", blank=True)
    address = models.CharField(max_length=256, verbose_name="Юридический адрес", blank=True)
    consumer_group = models.CharField(max_length=50, choices=CONSUMER_GROUP_CHOICES, verbose_name="Группа потребителей",
                                      default=LOCAL_BUDGET)

    class Meta:
        verbose_name_plural = 'Клиенты'

    def __str__(self):
        return self.name


class Contact(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='contacts', verbose_name="Клиент")
    contact = models.CharField(max_length=100, verbose_name="Контакт")

    def __str__(self):
        return self.contact


class Invoice(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='invoices', verbose_name="Клиент")
    ktt = models.FloatField(verbose_name="KTT")
    voltage = models.FloatField(verbose_name="Напряжение")
    start = models.FloatField(verbose_name="Начало")
    end = models.FloatField( verbose_name="Конец")
    xx = models.FloatField(verbose_name="XX")
    tariff = models.FloatField(verbose_name="Тариф")
    loss_xx = models.IntegerField(verbose_name="Потери XX", default=0)
    recalculation = models.IntegerField(verbose_name="Перерасчет")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Создан")

    @property
    def consumption(self):
        result = ((self.end - self.start) * self.ktt) * ((self.xx + 100) / 100)
        result = (100 + self.loss_xx) * result
        result = (100 + self.recalculation) * result
        return result / 10000

    @property
    def without_vat(self):
        return self.consumption * self.tariff

    class Meta:
        verbose_name = 'Счет'
        verbose_name_plural = 'Счета'

    def __str__(self):
        return f"Cчет за {self.created_at.strftime('%d.%m.%Y')} - Клиент:{self.client} "

calculator/forms.py
from django import forms
from django.forms import inlineformset_factory

from calculator.models import Client, Contact, Invoice

ContactFormSet = inlineformset_factory(Client, Contact, fields=('contact',), extra=1)

calculator/views.py
import json
from datetime import timezone

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.urls.base import reverse
from django.views.generic import ListView, CreateView, DetailView, TemplateView
from django.views import View
from openpyxl import Workbook
from openpyxl.styles import Font, Border, Side, Alignment
from openpyxl.writer.excel import save_virtual_workbook

from calculator.models import Client, Contact, Invoice
import openpyxl
from openpyxl.utils import get_column_letter


# Create your views here.
@login_required
def index(request):
    return render(request, 'calculator/home.html')


def create_contacts_from_json(client_instance, json_data):
    contacts_array = json.loads(json_data)
    for contact_data in contacts_array:
        contact = Contact.objects.create(client=client_instance, contact=contact_data['phone'])


def format_date(date):
    if date:
        return date.strftime('%d.%m.%Y')
    else:
        return None


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = '__all__'
    template_name = "calculator/create_client.html"
    success_url = reverse_lazy('clients')

    def form_valid(self, form):
        # Save client and contacts
        form.instance.user = self.request.user
        return self.save_with_contacts(form)

    def save_with_contacts(self, form):
        contacts_array = self.request.POST.get('contacts_array', None)
        if contacts_array:
            client_instance = form.save(commit=False)
            client_instance.save()
            create_contacts_from_json(client_instance, contacts_array)
        else:
            form.save()
        return super().form_valid(form)


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    context_object_name = 'clients'

    def get_queryset(self):
        queryset = Client.objects.all()
        search_query = self.request.GET.get('q')
        if search_query:
            queryset = queryset.filter(
                Q(bin_number__icontains=search_query) | Q(contract_number__icontains=search_query))
        return queryset

    template_name = 'calculator/clients.html'


class ClientDetailView(DetailView):
    model = Client
    template_name = 'calculator/client_detail.html'
    context_object_name = 'client'

    def get_queryset(self):
        return super().get_queryset().prefetch_related('invoices')


def export_checked_clients(request):
    if request.method == 'POST':
        selected_client_ids = request.POST.getlist('client_id')
        selected_clients = Client.objects.filter(pk__in=selected_client_ids)

        print(selected_clients)
        return json.dumps(selected_clients)


class CheckedClientsExportView(View):
    def post(self, request):
        selected_client_ids = request.POST.getlist('client_id')
        clients = Client.objects.filter(pk__in=selected_client_ids)
        # Create a new workbook
        wb = Workbook()
        ws = wb.active

        # Define the headers
        headers = [
            'Наименование клиента', 'Местоположение ПКУ', 'Информация по ПКУ', 'Дата акта', 'Напряжение (U)',
            'Начало показании', 'Конец показании', 'Расход', "Создан"
        ]

        # Write the headers to the worksheet
        ws.append(headers)

        # Make the header cells bold and apply border
        for row in ws.iter_rows(min_row=1, max_row=1):
            for cell in row:
                cell.font = Font(bold=True)
                cell.border = Border(bottom=Side(style='thin'))
                cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)

        # Write client data to the worksheet
        for client in clients:
            invoices = Invoice.objects.filter(client=client)
            for invoice in invoices:
                ws.append([
                    client.name,
                    client.location,
                    client.information,
                    format_date(client.contract_date),
                    invoice.voltage,
                    invoice.start,
                    invoice.end,
                    invoice.consumption,
                    format_date(invoice.created_at)
                ])

        # Apply border to all cells in the table
        for row in ws.iter_rows(min_row=1, max_row=len(clients) + 2, min_col=1, max_col=len(headers)):
            for cell in row:
                cell.border = Border(top=Side(style='thin'), bottom=Side(style='thin'), left=Side(style='thin'),
                                     right=Side(style='thin'))
                cell.alignment = Alignment(vertical='center', wrap_text=True)

        # Adjust column widths for better readability
        for col in ws.columns:
            max_length = 0
            column = col[0].column_letter
            for cell in col:
                try:
                    if len(str(cell.value)) > max_length:
                        max_length = len(cell.value)
                except:
                    pass
            adjusted_width = (max_length + 1) * 1.2
            ws.column_dimensions[column].width = adjusted_width

        # Save the workbook to a virtual file
        virtual_workbook = save_virtual_workbook(wb)

        # Return the Excel file as a response
        response = HttpResponse(
            virtual_workbook,
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
        response['Content-Disposition'] = 'attachment; filename=clients_invoices.xlsx'
        return response


class ClientExportView(View):
    def get(self, request, client_id):
        # Get the client by ID
        try:
            client = Client.objects.get(id=client_id)
        except Client.DoesNotExist:
            return HttpResponse("Client not found", status=404)

        invoices = Invoice.objects.filter(client=client)

        excel_data = self.export_invoices_to_excel(invoices)

        response = HttpResponse(
            excel_data,
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
        response['Content-Disposition'] = f'attachment; filename={client.name}_invoices.xlsx'
        return response

    def export_invoices_to_excel(self, invoices):
        # Create a new workbook
        wb = Workbook()
        ws = wb.active

        # Define the headers
        headers = [
            'Наименование клиента', 'Местоположение ПКУ', 'Информация по ПКУ', 'Дата акта', 'Напряжение (U)',
            'Начало показании', 'Конец показании', 'Расход', "Создан"
        ]

        # Write the headers to the worksheet
        ws.append(headers)

        # Make the header cells bold and apply border
        for row in ws.iter_rows(min_row=1, max_row=1):
            for cell in row:
                cell.font = Font(bold=True)
                cell.border = Border(bottom=Side(style='thin'))
                cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)

        # Write the invoice data to the worksheet
        for invoice in invoices:
            ws.append([
                invoice.client.name,
                invoice.client.location,
                invoice.client.information,
                format_date(invoice.client.contract_date),
                invoice.voltage,
                invoice.start,
                invoice.end,
                invoice.consumption,
                format_date(invoice.created_at)
            ])

        # Apply border to all cells in the table
        for row in ws.iter_rows(min_row=1, max_row=len(invoices) + 1, min_col=1, max_col=len(headers)):
            for cell in row:
                cell.border = Border(top=Side(style='thin'), bottom=Side(style='thin'), left=Side(style='thin'),
                                     right=Side(style='thin'))
                cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)

        # Calculate the total for the "Расход" column
        total_row = ['Total']
        for _ in range(len(headers) - 3):  # Skip the first empty cell
            total_row.append('')

        # Calculate the total for the "Расход" column
        total_consumption = sum(invoice.consumption for invoice in invoices)
        total_row.append(total_consumption)
        ws.append(total_row)

        # Apply border to the total row
        for row in ws.iter_rows(min_row=len(invoices) + 2, max_row=len(invoices) + 2, min_col=1, max_col=len(headers)):
            for cell in row:
                cell.border = Border(top=Side(style='thin'), bottom=Side(style='thin'), left=Side(style='thin'),
                                     right=Side(style='thin'))

        # Adjust column widths for better readability
        for col in ws.columns:
            max_length = 0
            column = col[0].column_letter
            for cell in col:
                try:
                    if len(str(cell.value)) > max_length:
                        max_length = len(cell.value)
                except:
                    pass
            adjusted_width = (max_length + 2) * 1.2
            ws.column_dimensions[column].width = adjusted_width

        # Save the workbook to a virtual file
        virtual_workbook = save_virtual_workbook(wb)
        return virtual_workbook


class InvoiceCreateView(LoginRequiredMixin, CreateView):
    model = Invoice
    fields = '__all__'
    template_name = 'calculator/create_invoice.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):

templates/calculator/create_client.html
{% extends 'base.html' %}
{% block content %}
    <div class="flex gap-3 flex-col w-1/4  mx-auto p-4 pt-6 md:p-6 lg:p-12 bg-white rounded shadow-md">
        <div class="text-3xl font-semibold">Добавить клиента</div>
        <form method="post">
            {% csrf_token %}
            <div class="mb-6">
                <label for="id_name"
                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Наименование</label>
                <input type="text" id="id_name" name="name" maxlength="100" required value="{{ client.name }}"
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
            </div>
            <div class="mb-6">
                <label for="id_bin_number" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">БИН
                    номер:</label>
                <input type="text" id="id_bin_number" name="bin_number" maxlength="12" required
                       value="{{ client.bin_number }}"
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
            </div>
            <div class="mb-6">
                <label for="id_information" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Информация
                    ПКУ:</label>
                <input type="text" id="id_information" name="information" maxlength="256"
                       value="{{ client.information }}"
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
            </div>
            <div class="mb-6">
                <label for="id_contract_number" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Номер
                    договора:</label>
                <input type="text" id="id_contract_number" name="contract_number" maxlength="50"
                       required value="{{ client.contract_number }}"
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
            </div>
            <label for="id_contract_date" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Дата
                акта:</label>
            <div class="relative w-full mb-6">
                <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                    <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
                    </svg>
                </div>

                <input datepicker datepicker-format="dd.mm.yyyy" type="text" id="id_contract_date" name="contract_date"
                       autocomplete="off" value="{{ client.contract_date }}"
                       required
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                       placeholder="Выберите дату">
            </div>
            <div class="mb-6">
                <label for="id_location" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Местоположение
                    ПКУ:</label>
                <input type="text" id="id_location" name="location" maxlength="128" value="{{ client.location }}"
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
            </div>
            <div class="mb-6">
                <label for="id_address"
                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Юридический адрес:</label>
                <input type="text" id="id_address" name="address" maxlength="256" value="{{ client.address }}"
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
            </div>
            <div class="mb-6">
                <label for="id_consumer_group" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Группа
                    потребителей:</label>
                <select id="id_consumer_group" name="consumer_group"
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                    {% for choice in form.consumer_group.field.choices %}
                        {% if choice.0 == client.consumer_group %}
                            <option selected value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% else %}
                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="mb-6">
                <label for="id_notes"
                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Примечания:</label>
                <input type="text" id="id_notes" name="notes" maxlength="256" value="{{ client.notes }}"
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
            </div>
            <!-- Contact formset -->
            <input type="hidden" name="contacts_array" id="contactsArrayInput">

            <div class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Контакты:</div>
            <table id="contactsTable" class="text-gray-500 w-full text-sm text-left">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3">Телефон</th>
                    <th scope="col" class="px-6 py-3">Действие</th>
                </tr>
                </thead>
                <tbody>
                {% if client.contacts %}
                    {% for contact in client.contacts.all %}
                        <tr>
                            <td class="px-3 py-4">
                                <input type='text' value="{{ contact }}"
                                       class='bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'>
                            </td>
                            <td>
                                <button onclick='deleteContact(this)'
                                        class='focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900'>
                                    Удалить
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td class="px-3 py-4">
                            <input type='text'
                                   class='bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'>
                        </td>
                        <td>
                            <button onclick='deleteContact(this)'
                                    class='focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900'>
                                Удалить
                            </button>
                        </td>
                    </tr>
                {% endif %}


                </tbody>
            </table>
            <button onclick="addContact()" type="button"
                    class="text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">
                Добавить контакт
            </button>

            <div>
                <button type="submit" onclick="submitContacts()"
                        class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">
                    Сохранить
                </button>
            </div>
        </form>
    </div>

    <script>
        function addContact() {
            var table = document.getElementById("contactsTable").getElementsByTagName('tbody')[0];
            var row = table.insertRow(-1);
            var cell1 = row.insertCell(0);
            var cell2 = row.insertCell(1);
            cell1.classList.add("px-3", "py-4");
            cell2.classList.add("px-3", "py-4");
            cell1.innerHTML = "<input type='text' class='bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'>";
            cell2.innerHTML = "<button onclick='deleteContact(this)' class='focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900'>Удалить</button>";
        }

        function deleteContact(row) {
            var rowIndex = row.parentNode.parentNode.rowIndex;
            document.getElementById("contactsTable").deleteRow(rowIndex);
        }

        function submitContacts() {
            var table = document.getElementById("contactsTable");
            var contactsArray = [];
            for (var i = 1; i < table.rows.length; i++) {
                var contact = {
                    phone: table.rows[i].cells[0].getElementsByTagName("input")[0].value
                };
                contactsArray.push(contact);
            }
            document.getElementById("contactsArrayInput").value = JSON.stringify(contactsArray);
        }
    </script>
{% endblock content %}

templates/calculator/home.html
{% extends 'base.html' %}
{% block content %}
    <br>

<div class="text-3xl ">Добро пожаловать {{ user }}</div>
{% endblock content %}

templates/calculator/invoice_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
  <div class="max-w mx-auto p-4 pt-6 md:p-6 lg:p-12 bg-white rounded shadow-md">
    <h1 class="text-3xl font-bold mb-4">Результаты счета</h1>
    <div class="flex flex-col flex-wrap -mx-3 mb-6">
      <div class="w-full md:w-1/2 xl:w-1/2 p-3">
        <p class="text-lg font-medium">Потребление:</p>
        <p class="text-2xl font-bold">{{ invoice.consumption | floatformat:2 | intcomma  }}</p>
      </div>
      <div class="w-full md:w-1/2 xl:w-1/2 p-3">
        <p class="text-lg font-medium">Без НДС:</p>
        <p class="text-2xl font-bold">{{ invoice.without_vat | floatformat:2 | intcomma }}</p>
      </div>
    </div>
  </div>
{% endblock %}